import type { Metadata } from 'next'
import './globals.css'
import { Barlow, Poppins } from 'next/font/google'
import { Navbar } from '@/components'

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
  subsets: ['latin'],
})

const barlow = Barlow({
  weight: ['400', '500', '600', '700'],
  variable: '--font-barlow',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${barlow.variable} antialiased font-barlow`}
      >
        <Navbar />
        <div className="bg-[#F9FAFC] mt-12">{children}</div>
      </body>
    </html>
  )
}
